app:
  name: conv-app
  image: antonlarichev/conv-app
  version: v1.0
  replicas: 3
  port: 80
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "128Mi"
      cpu: "100m"