apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    components: rabbitmq
  ports:
    - name: port15691
      port: 15691
      targetPort: 15691
      protocol: TCP
    
    - name: port15692
      port: 15692
      targetPort: 15692
      protocol: TCP

    - name: port15672
      port: 15672
      targetPort: 15672
      protocol: TCP
    
    - name: port25672
      port: 25672
      targetPort: 25672
      protocol: TCP
    
    - name: port4369
      port: 4369
      targetPort: 4369
      protocol: TCP
    
    - name: port5671
      port: 5671
      targetPort: 5671
      protocol: TCP
    
    - name: port5672
      port: 5672
      targetPort: 5672
      protocol: TCP
