apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: conv-app
spec:
  containers:
  - name: conv-app
    image: antonlarichev/conv-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
