apiVersion: v1
kind: Service
metadata:
  name: conv-api-clusterip
spec:
  type: ClusterIP
  selector:
    app: conv-api
  ports:
    - name: port80
      port: 80
      targetPort: 80
      protocol: TCP
